//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LsitPhone
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListPhone
    {
        public int id_listphone { get; set; }
        public string LSurname { get; set; }
        public string LName { get; set; }
        public string LPobatkovi { get; set; }
        public string LEmail { get; set; }
        public int id_country { get; set; }
        public int LPhone { get; set; }
        public System.DateTime LDateBrith { get; set; }
        public System.DateTime LAddDate { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
